[package]
name = "aegisub-scuisei"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"
license = "MIT"
publish = false

[lib]
name = "aegisub_scuisei"
path = "../src/aegisub.rs"
crate-type = ["staticlib"]

[dependencies]
wide = "=1.1.1"
rayon = "=1.10.0"
anyhow = "=1.0.95"
thiserror = "=2.0.11"

[dev-dependencies]
proptest = "=1.6.0"

[profile.release]
opt-level = 3
panic = "unwind"

